spring.application.name=boardgames-app
server.port=8080

# Conexion dinamica a MySQL via variables de entorno
spring.datasource.url=jdbc:mysql://${DB_HOST:mysql_container}:${DB_PORT:3306}/${DB_NAME:semocho}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:rootpassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect